### ISSUE TITLE
dockWidget

### ISSUE THREAD

**Issue by Caprey** [b-steiner/styled_qt_controls#18]
the dock widget  of this project packed as a library,or make a independent project?

**Comment by b-steiner** [comment]
Hello,

Since the dock widget uses several of the other controls in this library, it is not easily possible to make it a stand-alone control.
The project itself is already compiled as a library (and can be downloaded as part of the sample application). You can also build it from source.

I'm not doing any active development on the project at the moment since I got a new job and don't work with C++/Qt anymore.

kind regards,
b-steiner

**Comment by Caprey** [comment]
thanks!
